"""
Mela AI - Pydantic Schemas
"""

from app.schemas.auth import (
    TokenData,
    UserInfo,
    UserCreate,
    UserUpdate,
    UserResponse,
    LoginResponse,
)
from app.schemas.chat import (
    MessageRole,
    ModelOption,
    Attachment,
    Citation,
    ToolCall,
    ToolResult,
    ChatMessage,
    ChatRequest,
    ChatResponse,
    StreamChunk,
    ConversationCreate,
    ConversationUpdate,
    ConversationResponse,
    ConversationDetail,
    MessageResponse,
    ModelInfo,
)
from app.schemas.documents import (
    DocumentSource,
    DocumentStatus,
    DocumentUpload,
    DocumentResponse,
    DocumentChunkResponse,
    SearchResult,
    SearchRequest,
    SearchResponse,
    IndexingStatus,
    SharePointSyncRequest,
    SharePointSyncStatus,
)
from app.schemas.admin import (
    UsageStats,
    DailyUsage,
    ModelUsageStats,
    UserUsageStats,
    AnalyticsResponse,
    AuditLogResponse,
    AuditLogFilter,
    ToolConfigResponse,
    ToolConfigUpdate,
    SystemSettingResponse,
    SystemSettingUpdate,
    ModelConfigResponse,
)

__all__ = [
    # Auth
    "TokenData",
    "UserInfo",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "LoginResponse",
    # Chat
    "MessageRole",
    "ModelOption",
    "Attachment",
    "Citation",
    "ToolCall",
    "ToolResult",
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "StreamChunk",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ConversationDetail",
    "MessageResponse",
    "ModelInfo",
    # Documents
    "DocumentSource",
    "DocumentStatus",
    "DocumentUpload",
    "DocumentResponse",
    "DocumentChunkResponse",
    "SearchResult",
    "SearchRequest",
    "SearchResponse",
    "IndexingStatus",
    "SharePointSyncRequest",
    "SharePointSyncStatus",
    # Admin
    "UsageStats",
    "DailyUsage",
    "ModelUsageStats",
    "UserUsageStats",
    "AnalyticsResponse",
    "AuditLogResponse",
    "AuditLogFilter",
    "ToolConfigResponse",
    "ToolConfigUpdate",
    "SystemSettingResponse",
    "SystemSettingUpdate",
    "ModelConfigResponse",
]
