#!/bin/bash
#
# Mela AI - Azure Deployment Script
# Deploys all infrastructure and applications
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
ENVIRONMENT="dev"
LOCATION="eastus2"
ORG_PREFIX="armely"
PROJECT_NAME="mela"

# Print with color
print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Help text
show_help() {
    echo "Mela AI - Azure Deployment Script"
    echo ""
    echo "Usage: ./deploy.sh [options]"
    echo ""
    echo "Options:"
    echo "  -e, --environment    Environment (dev, staging, prod) [default: dev]"
    echo "  -l, --location       Azure region [default: eastus2]"
    echo "  -o, --org            Organization prefix [default: armely]"
    echo "  -p, --project        Project name [default: mela]"
    echo "  -h, --help           Show this help message"
    echo ""
    echo "Example:"
    echo "  ./deploy.sh -e prod -l westus2"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -e|--environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        -l|--location)
            LOCATION="$2"
            shift 2
            ;;
        -o|--org)
            ORG_PREFIX="$2"
            shift 2
            ;;
        -p|--project)
            PROJECT_NAME="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Validate environment
if [[ ! "$ENVIRONMENT" =~ ^(dev|staging|prod)$ ]]; then
    print_error "Invalid environment: $ENVIRONMENT"
    exit 1
fi

# Resource names
RESOURCE_PREFIX="${ORG_PREFIX}-${PROJECT_NAME}-${ENVIRONMENT}"
RESOURCE_GROUP="rg-${RESOURCE_PREFIX}"

print_info "Starting Mela AI deployment..."
print_info "Environment: $ENVIRONMENT"
print_info "Location: $LOCATION"
print_info "Resource Group: $RESOURCE_GROUP"

# Check Azure CLI
if ! command -v az &> /dev/null; then
    print_error "Azure CLI is not installed. Please install it first."
    exit 1
fi

# Check login status
print_info "Checking Azure login status..."
if ! az account show &> /dev/null; then
    print_warning "Not logged in. Starting login..."
    az login
fi

# Get subscription and tenant info
SUBSCRIPTION_ID=$(az account show --query id -o tsv)
TENANT_ID=$(az account show --query tenantId -o tsv)

print_info "Subscription ID: $SUBSCRIPTION_ID"
print_info "Tenant ID: $TENANT_ID"

# Prompt for required parameters
echo ""
read -p "Enter Azure AD Client ID for authentication: " ENTRA_CLIENT_ID
read -p "Enter admin email for alerts: " ADMIN_EMAIL

if [[ -z "$ENTRA_CLIENT_ID" ]]; then
    print_error "Azure AD Client ID is required"
    exit 1
fi

# Deploy infrastructure
print_info "Deploying Azure infrastructure..."

az deployment sub create \
    --name "mela-${ENVIRONMENT}-$(date +%Y%m%d%H%M%S)" \
    --location "$LOCATION" \
    --template-file infrastructure/bicep/main.bicep \
    --parameters \
        environment="$ENVIRONMENT" \
        location="$LOCATION" \
        orgPrefix="$ORG_PREFIX" \
        projectName="$PROJECT_NAME" \
        tenantId="$TENANT_ID" \
        entraClientId="$ENTRA_CLIENT_ID" \
        adminEmail="$ADMIN_EMAIL"

print_success "Infrastructure deployment completed!"

# Get outputs
print_info "Retrieving deployment outputs..."

DEPLOYMENT_OUTPUTS=$(az deployment sub show \
    --name "mela-${ENVIRONMENT}-$(date +%Y%m%d)" \
    --query properties.outputs \
    -o json 2>/dev/null || echo "{}")

KEY_VAULT_NAME=$(echo "$DEPLOYMENT_OUTPUTS" | jq -r '.keyVaultName.value // empty')
STORAGE_NAME=$(echo "$DEPLOYMENT_OUTPUTS" | jq -r '.storageAccountName.value // empty')
BACKEND_URL=$(echo "$DEPLOYMENT_OUTPUTS" | jq -r '.backendUrl.value // empty')
FRONTEND_URL=$(echo "$DEPLOYMENT_OUTPUTS" | jq -r '.frontendUrl.value // empty')

print_info "Key Vault: $KEY_VAULT_NAME"
print_info "Storage Account: $STORAGE_NAME"
print_info "Backend URL: $BACKEND_URL"
print_info "Frontend URL: $FRONTEND_URL"

# Create .env file for local development
print_info "Generating .env file for local development..."

cat > .env.local << EOF
# Mela AI - Local Development Environment
# Generated by deploy.sh on $(date)

# Azure Settings
AZURE_TENANT_ID=$TENANT_ID
AZURE_CLIENT_ID=$ENTRA_CLIENT_ID
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID

# Key Vault
AZURE_KEY_VAULT_NAME=$KEY_VAULT_NAME

# API Settings
API_URL=$BACKEND_URL
NEXT_PUBLIC_API_URL=$BACKEND_URL

# Frontend URL
FRONTEND_URL=$FRONTEND_URL
EOF

print_success ".env.local file created!"

# Next steps
echo ""
print_success "🎉 Mela AI deployment completed successfully!"
echo ""
print_info "Next steps:"
echo "  1. Configure Azure AD app registration redirect URIs:"
echo "     - $BACKEND_URL/api/auth/callback"
echo "     - $FRONTEND_URL"
echo ""
echo "  2. Deploy the backend application:"
echo "     cd backend && ./deploy-backend.sh"
echo ""
echo "  3. Deploy the frontend application:"
echo "     cd frontend && npm run deploy"
echo ""
echo "  4. Access your application:"
echo "     Frontend: $FRONTEND_URL"
echo "     Backend:  $BACKEND_URL"
echo ""
