#!/usr/bin/env bash
# =============================================================================
# scripts/scan-resources.sh — Mela AI Resource Scanner
# Scans the repository for environment variable references to determine
# which Azure services are required. Outputs docs/resources-required.md
# and scripts/resource-inventory.json.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOCS_DIR="$REPO_ROOT/docs"
OUTPUT_MD="$DOCS_DIR/resources-required.md"
OUTPUT_JSON="$SCRIPT_DIR/resource-inventory.json"

mkdir -p "$DOCS_DIR"

echo "Scanning repository for Azure resource requirements..."

# ── Helper: grep for a key in the repo ────────────────────────────────────────
key_used() {
  local key="$1"
  grep -rq "$key" "$REPO_ROOT/backend" "$REPO_ROOT/frontend" \
       --include="*.py" --include="*.ts" --include="*.tsx" --include="*.js" \
       --include="*.env*" --include="*.sample" 2>/dev/null
}

# ── Detect required services ───────────────────────────────────────────────────
NEEDS_OPENAI=false
NEEDS_SPEECH=false
NEEDS_DALLE=false
NEEDS_SEARCH=false
NEEDS_STORAGE=false
NEEDS_SQL=false
NEEDS_COSMOS=false
NEEDS_REDIS=false
NEEDS_TRANSLATOR=false
NEEDS_DOC_INTELLIGENCE=false
NEEDS_APPINSIGHTS=false
NEEDS_KEYVAULT=false

key_used "AI_FOUNDRY_ENDPOINT\|AZURE_OPENAI_ENDPOINT\|AZURE_OPENAI_API_KEY"    && NEEDS_OPENAI=true
key_used "AZURE_SPEECH_KEY\|AZURE_SPEECH_ENDPOINT"                             && NEEDS_SPEECH=true
key_used "AZURE_DALLE"                                                          && NEEDS_DALLE=true
key_used "AZURE_SEARCH_ENDPOINT\|AZURE_SEARCH_API_KEY\|AZURE_SEARCH_ADMIN_KEY" && NEEDS_SEARCH=true
key_used "AZURE_STORAGE_ACCOUNT\|AZURE_STORAGE_CONNECTION\|BLOB_CONTAINER"     && NEEDS_STORAGE=true
key_used "AZURE_SQL_SERVER\|DATABASE_URL"                                       && NEEDS_SQL=true
key_used "AZURE_COSMOS_ENDPOINT\|COSMOS_ENDPOINT"                               && NEEDS_COSMOS=true
key_used "REDIS_URL\|AZURE_REDIS"                                               && NEEDS_REDIS=true
key_used "AZURE_TRANSLATOR_KEY\|AZURE_TRANSLATOR_ENDPOINT"                      && NEEDS_TRANSLATOR=true
key_used "AZURE_DOCUMENT_INTELLIGENCE"                                          && NEEDS_DOC_INTELLIGENCE=true
key_used "APPLICATIONINSIGHTS_CONNECTION_STRING\|APP_INSIGHTS"                  && NEEDS_APPINSIGHTS=true
key_used "AZURE_KEY_VAULT\|KEY_VAULT"                                           && NEEDS_KEYVAULT=true

# ── Write Markdown report ──────────────────────────────────────────────────────
cat > "$OUTPUT_MD" << 'HEADER'
# Mela AI — Azure Resources Required

> Auto-generated by `scripts/scan-resources.sh`. Re-run after adding new integrations.

## Architecture Overview

This application deploys as two Azure App Service instances (Linux):
- **armely-ai-api** — FastAPI backend (Python 3.12)
- **armely-ai-web** — Next.js 14 frontend (Node.js 20 LTS)

Both share a single App Service Plan (`asp-armely-ai`) and a Key Vault (`kv-armely-ai`).

HEADER

echo "" >> "$OUTPUT_MD"
echo "## Required Resources Detected in Codebase" >> "$OUTPUT_MD"
echo "" >> "$OUTPUT_MD"
echo "| Resource | Required Local | Required Prod | Where Configured |" >> "$OUTPUT_MD"
echo "|----------|:---:|:---:|---|" >> "$OUTPUT_MD"
echo "| App Service Plan (asp-armely-ai) | — | ✓ | Bicep auto-provisioned |" >> "$OUTPUT_MD"
echo "| Backend Web App (armely-ai-api) | — | ✓ | Bicep auto-provisioned |" >> "$OUTPUT_MD"
echo "| Frontend Web App (armely-ai-web) | — | ✓ | Bicep auto-provisioned |" >> "$OUTPUT_MD"
echo "| Key Vault (kv-armely-ai) | — | ✓ | Bicep auto-provisioned |" >> "$OUTPUT_MD"
echo "| App Insights (ai-armely-ai) | ✗ | ✓ | Bicep auto-provisioned |" >> "$OUTPUT_MD"

[ "$NEEDS_SQL" = true ]              && echo "| Azure SQL / DATABASE_URL | SQLite | ✓ | env/.env.local → KV secret: database-url |" >> "$OUTPUT_MD"
[ "$NEEDS_OPENAI" = true ]           && echo "| Azure OpenAI / AI Foundry | ✓ | ✓ | env/.env.local → KV secret: ai-foundry-api-key |" >> "$OUTPUT_MD"
[ "$NEEDS_SPEECH" = true ]           && echo "| Azure Cognitive Speech | ✗ | ✓ | env/.env.local → KV secret: azure-speech-key |" >> "$OUTPUT_MD"
[ "$NEEDS_DALLE" = true ]            && echo "| Azure DALL-E (Image Generation) | ✗ | ✓ | env/.env.local → KV secret: azure-dalle-api-key |" >> "$OUTPUT_MD"
[ "$NEEDS_SEARCH" = true ]           && echo "| Azure AI Search | ✗ | ✓ | env/.env.local → KV secret: azure-search-admin-key |" >> "$OUTPUT_MD"
[ "$NEEDS_STORAGE" = true ]          && echo "| Azure Blob Storage | ✗ | ✓ | env/.env.local → KV secret: azure-storage-account-key |" >> "$OUTPUT_MD"
[ "$NEEDS_COSMOS" = true ]           && echo "| Azure Cosmos DB | ✗ | Optional | env/.env.local |" >> "$OUTPUT_MD"
[ "$NEEDS_REDIS" = true ]            && echo "| Azure Cache for Redis | ✗ | Optional | env/.env.local |" >> "$OUTPUT_MD"
[ "$NEEDS_TRANSLATOR" = true ]       && echo "| Azure Translator | ✗ | ✓ | env/.env.local |" >> "$OUTPUT_MD"
[ "$NEEDS_DOC_INTELLIGENCE" = true ] && echo "| Azure Document Intelligence | ✗ | ✓ | env/.env.local |" >> "$OUTPUT_MD"

echo "" >> "$OUTPUT_MD"

cat >> "$OUTPUT_MD" << 'FOOTER'
## Environment Variable Mapping

| Variable | Purpose | Local | Prod |
|----------|---------|:-----:|:----:|
| `AZURE_TENANT_ID` | Entra ID tenant | env/.env.local | App Setting |
| `AZURE_CLIENT_ID` | Entra app client ID | env/.env.local | App Setting |
| `AZURE_CLIENT_SECRET` | Entra app secret | env/.env.local | KV: azure-client-secret |
| `AI_FOUNDRY_ENDPOINT` | Azure AI Foundry URL | env/.env.local | App Setting |
| `AI_FOUNDRY_API_KEY` | Azure AI Foundry key | env/.env.local | KV: ai-foundry-api-key |
| `AZURE_OPENAI_ENDPOINT` | OpenAI endpoint | env/.env.local | App Setting |
| `AZURE_OPENAI_API_KEY` | OpenAI API key | env/.env.local | KV: azure-openai-api-key |
| `AZURE_SPEECH_KEY` | Speech service key | env/.env.local | KV: azure-speech-key |
| `AZURE_SPEECH_REGION` | Speech region | env/.env.local | App Setting |
| `AZURE_DALLE_ENDPOINT` | DALL-E endpoint | env/.env.local | App Setting |
| `AZURE_DALLE_API_KEY` | DALL-E key | env/.env.local | KV: azure-dalle-api-key |
| `AZURE_SEARCH_ENDPOINT` | AI Search endpoint | env/.env.local | App Setting |
| `AZURE_SEARCH_ADMIN_KEY` | AI Search admin key | env/.env.local | KV: azure-search-admin-key |
| `DATABASE_URL` | Database connection string | SQLite (auto) | KV: database-url |
| `JWT_SECRET_KEY` | JWT signing key | auto-generated (dev) | KV: jwt-secret-key |
| `APPLICATIONINSIGHTS_CONNECTION_STRING` | App Insights | optional | App Setting (Bicep) |
| `AZURE_KEY_VAULT_NAME` | Key Vault name | optional | App Setting (Bicep) |
| `NEXT_PUBLIC_API_URL` | Backend URL for frontend | http://localhost:8000 | App Setting (Bicep) |
| `NEXT_PUBLIC_AZURE_AD_CLIENT_ID` | MSAL client ID | env/.env.local (frontend) | App Setting (frontend) |
| `NEXT_PUBLIC_AZURE_AD_TENANT_ID` | MSAL tenant ID | env/.env.local (frontend) | App Setting (frontend) |

## External Dependencies (Not Auto-Provisioned)

These must be manually provisioned or provided:

- [ ] Azure AI Foundry deployment (models: gpt-4.1, Kimi-K2.5, Mistral-Large-3, text-embedding-3-small, dall-e-3)
- [ ] Azure AI Search index (optional; needed for enterprise RAG)
- [ ] Azure SQL Database (optional; SQLite used for local dev)
- [ ] Azure Cognitive Speech resource
- [ ] Azure Document Intelligence resource
- [ ] Entra app registration (Meeting-Intelligence-Bot) — tenant: 588cadf4-9902-4465-86c0-8bcf04f4f102

## Key Vault Secrets Checklist

Run this after Bicep provisioning to populate secrets:

```bash
KV=kv-armely-ai
az keyvault secret set --vault-name $KV --name jwt-secret-key         --value "$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
az keyvault secret set --vault-name $KV --name azure-client-secret    --value "$AZURE_CLIENT_SECRET"
az keyvault secret set --vault-name $KV --name ai-foundry-api-key     --value "$AI_FOUNDRY_API_KEY"
az keyvault secret set --vault-name $KV --name azure-openai-api-key   --value "$AZURE_OPENAI_API_KEY"
az keyvault secret set --vault-name $KV --name azure-speech-key       --value "$AZURE_SPEECH_KEY"
az keyvault secret set --vault-name $KV --name azure-dalle-api-key    --value "$AZURE_DALLE_API_KEY"
az keyvault secret set --vault-name $KV --name azure-search-admin-key --value "$AZURE_SEARCH_ADMIN_KEY"
az keyvault secret set --vault-name $KV --name database-url           --value "$DATABASE_URL"
```
FOOTER

echo "Written: $OUTPUT_MD"

# ── Write JSON inventory ───────────────────────────────────────────────────────
cat > "$OUTPUT_JSON" << JSON
{
  "generatedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "services": {
    "azureOpenAI":          $NEEDS_OPENAI,
    "azureSpeech":          $NEEDS_SPEECH,
    "azureDalle":           $NEEDS_DALLE,
    "azureSearch":          $NEEDS_SEARCH,
    "azureStorage":         $NEEDS_STORAGE,
    "azureSql":             $NEEDS_SQL,
    "azureCosmos":          $NEEDS_COSMOS,
    "redis":                $NEEDS_REDIS,
    "azureTranslator":      $NEEDS_TRANSLATOR,
    "documentIntelligence": $NEEDS_DOC_INTELLIGENCE,
    "appInsights":          $NEEDS_APPINSIGHTS,
    "keyVault":             $NEEDS_KEYVAULT
  }
}
JSON

echo "Written: $OUTPUT_JSON"
echo "Done."
