"""Redis-backed active conversation context cache.

Replaces the module-level ``_in_memory_messages`` dict in ``chat_service.py``
with a Redis List so active context survives replica restarts and is shared
across all instances of the app.

Key schema:
    ``{PREFIX}ctx:{conversation_id}``  → Redis List of JSON strings, newest last.
    TTL: 3 600 s, sliding — refreshed on every read/write.

The list is trimmed to the last ``max_messages`` elements (default 20) on every
write so memory is bounded even for very long conversations.

Security: ``conversation_id`` is an internal UUID generated by the backend; it
is never derived from user-supplied data, so there is no injection surface.

Fallback: every public function accepts an ``_fallback`` dict that callers may
pass their ``_in_memory_messages`` reference into.  When Redis is unavailable,
the function reads/writes the fallback dict transparently.
"""
from __future__ import annotations

import json
import logging
from typing import Optional

from app.core.redis_client import get_redis, key as rkey

logger = logging.getLogger(__name__)

_CTX_TTL_SECONDS = 3600
_DEFAULT_MAX_MESSAGES = 20


def _ctx_key(conversation_id: str) -> str:
    return rkey("ctx", conversation_id)


async def get_active_context(
    conversation_id: str,
    max_messages: int = _DEFAULT_MAX_MESSAGES,
    _fallback: Optional[dict] = None,
) -> list[dict]:
    """Return the last ``max_messages`` messages for a conversation.

    Returns an empty list on cache miss.  Callers should fall through to
    their DB-backed context retrieval on an empty result.
    """
    r = await get_redis()
    if r is None:
        if _fallback is not None:
            return list(_fallback.get(conversation_id, []))
        return []
    try:
        raw_list = await r.lrange(_ctx_key(conversation_id), -max_messages, -1)
        if raw_list:
            # Slide the TTL on every successful read.
            await r.expire(_ctx_key(conversation_id), _CTX_TTL_SECONDS)
        return [json.loads(m) for m in raw_list]
    except Exception as exc:
        logger.warning("context_cache get error (%s); returning empty", exc)
        if _fallback is not None:
            return list(_fallback.get(conversation_id, []))
        return []


async def append_message_to_context(
    conversation_id: str,
    message: dict,
    max_messages: int = _DEFAULT_MAX_MESSAGES,
    _fallback: Optional[dict] = None,
) -> None:
    """Append a single message to the active context list.

    Uses an atomic pipeline (RPUSH + LTRIM + EXPIRE) so no partial state is
    left if the connection drops mid-operation.
    """
    r = await get_redis()
    if r is None:
        if _fallback is not None:
            _fallback.setdefault(conversation_id, [])
            _fallback[conversation_id].append(message)
        return
    try:
        k = _ctx_key(conversation_id)
        async with r.pipeline(transaction=True) as pipe:
            pipe.rpush(k, json.dumps(message))
            pipe.ltrim(k, -max_messages, -1)
            pipe.expire(k, _CTX_TTL_SECONDS)
            await pipe.execute()
    except Exception as exc:
        logger.warning("context_cache append error (%s); falling back to in-process", exc)
        if _fallback is not None:
            _fallback.setdefault(conversation_id, [])
            _fallback[conversation_id].append(message)


async def set_context(
    conversation_id: str,
    messages: list[dict],
    max_messages: int = _DEFAULT_MAX_MESSAGES,
    _fallback: Optional[dict] = None,
) -> None:
    """Overwrite the entire context for a conversation.

    Used when chat_service rebuilds context from DB on a cache miss.
    """
    r = await get_redis()
    if r is None:
        if _fallback is not None:
            _fallback[conversation_id] = list(messages[-max_messages:])
        return
    try:
        k = _ctx_key(conversation_id)
        trimmed = messages[-max_messages:]
        async with r.pipeline(transaction=True) as pipe:
            pipe.delete(k)
            if trimmed:
                pipe.rpush(k, *[json.dumps(m) for m in trimmed])
            pipe.expire(k, _CTX_TTL_SECONDS)
            await pipe.execute()
    except Exception as exc:
        logger.warning("context_cache set error (%s); falling back to in-process", exc)
        if _fallback is not None:
            _fallback[conversation_id] = list(messages[-max_messages:])


async def invalidate_context(conversation_id: str, _fallback: Optional[dict] = None) -> None:
    """Delete the context cache entry for a conversation."""
    r = await get_redis()
    if r is None:
        if _fallback is not None:
            _fallback.pop(conversation_id, None)
        return
    try:
        await r.delete(_ctx_key(conversation_id))
    except Exception as exc:
        logger.warning("context_cache invalidate error (%s)", exc)
    if _fallback is not None:
        _fallback.pop(conversation_id, None)
